matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .github/workflows/configs/wordlists/author-names.txt
        - .github/workflows/configs/wordlists/project-names.txt
        - .github/workflows/configs/wordlists/brand-names.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "**/README.md"
      - "**/CODE-OF-CONDUCT.md"
      - "**/CONTRIBUTING.md"
    default_encoding: utf-8
