name: Check Markdown

on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Ruby Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install awesome_bot
        run: gem install awesome_bot
      - name: Check links with awesomebot
        run: awesome_bot README.md --allow-redirect --base-url="https://github.com/ilanfriedman/Awesome-Adobe-Plugins/blob/master/"
  spell-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Initialize Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install CSpell
        run: npm install -g cspell
      - name: Run CSpell
        run: cspell --config ./.github/workflows/configs/.cspell.yaml "**/*.md" --show-suggestions --git-ignore
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: .github/workflows/configs/.markdownlint.yaml
          args: "**/*.md"
          ignore: LICENSE.md
          fix: true
          output: .github/workflows/.workflow-output/markdownlint-output.txt
