name: Check Markdown

on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Ruby Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install awesome_bot
        run: gem install awesome_bot
      - name: Check links with awesomebot
        run: awesome_bot README.md --allow-redirect --base-url="https://github.com/ilanfriedman/Awesome-Adobe-Plugins/blob/master/"
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Spell Check Time!
        uses: rojopolis/spellcheck-github-actions@0.24.0
        with:
          task_name: Markdown
          source_files: README.md CODE-OF-CONDUCT.md CONTRIBUTING.md LICENSE.md
          output_file: .github/workflows/workflow-output/spellcheck-output.txt
          config_path: .github/workflows/configs/.spellcheck.yaml
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: .github/workflows/configs/.markdownlint.yaml
          args: "**/*.md"
          ignore: LICENSE.md
          fix: true
          output: .github/workflows/workflow-output/markdownlint-output.txt
